### ISSUE TITLE
Run without Node?? In  Browser?

### ISSUE THREAD

**Issue by villanus** [bubkoo/string-to-path#1]
Is there a way to get this to run in the browser?  Without nodeJs?
I am on the Microsoft / ASP.net side, and have zero experience doing things on the node world.

Thanks in advance!!

**Comment by bubkoo** [comment]
@villanus 

Using [browserify](http://browserify.org/) or [webpack](https://webpack.github.io/)  wrap this model.

**Comment by kevin1121** [comment]
多行文本生成svg path怎样设置行间距？

**Comment by kevin1121** [comment]
多行文本生成svg path怎样设置行间距?

**Comment by s1728k** [comment]
hi i get some error while  build

it seems require('fs'); is not getting dependency resolved
